options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _REGION: us-central1
  _SERVICE: mini-backend
  _REPO: app-repo

steps:

# Build backend image
- name: gcr.io/cloud-builders/docker
  args:
    - build
    - -t
    - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/backend:$COMMIT_SHA
    - ./backend

# Push image
- name: gcr.io/cloud-builders/docker
  args:
    - push
    - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/backend:$COMMIT_SHA

# Deploy Cloud Run
- name: gcr.io/google.com/cloudsdktool/cloud-sdk
  entrypoint: gcloud
  args:
    - run
    - deploy
    - ${_SERVICE}
    - --image=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/backend:$COMMIT_SHA
    - --region=${_REGION}
    - --platform=managed
    - --allow-unauthenticated

# Build frontend
- name: node:18
  dir: frontend
  args:
    - bash
    - -c
    - |
      npm install
      npm run build

# Deploy Firebase Hosting
- name: gcr.io/google.com/cloudsdktool/cloud-sdk
  dir: frontend
  entrypoint: bash
  args:
    - -c
    - |
      npm install -g firebase-tools
      firebase deploy --only hosting --project $PROJECT_ID --token $$FIREBASE_TOKEN